config/routes.rb
Rails.application.routes.draw do


  namespace :km do
    get 'user_manuals/index'
    get 'user_manuals/new'
    get 'user_manuals/edit'
  end
  namespace :risk do
    get 'user_manuals/index'
    get 'user_manuals/new'
    get 'user_manuals/edit'
  end
  namespace :pmqa do
    get 'user_manuals/index'
    get 'user_manuals/new'
    get 'user_manuals/edit'
  end
  namespace :kpi do
    get 'user_manuals/index'
    get 'user_manuals/edit'
    get 'user_manuals/new'
  end
  namespace :risk do
    get 'list_risk_types/index'
    get 'list_risk_types/show'
    get 'list_risk_types/edit'
    get 'list_risk_types/new'
  end
  namespace :risk do
    get 'list_risk_factors/index'
    get 'list_risk_factors/show'
    get 'list_risk_factors/edit'
    get 'list_risk_factors/new'
  end
  namespace :kpi do
    get 'period_reports/index'
    get 'period_reports/show'
    get 'period_reports/new'
    get 'period_reports/edit'
  end
  namespace :risk do
    namespace :control do
      get 'period_reports/index'
      get 'period_reports/show'
      get 'period_reports/new'
      get 'period_reports/edit'
    end
  end
  get 'errors/not_found'
  get 'errors/internal_server_error'
  resources :locations
  resources :bizs
  ["km", "kpi", "risk", "pmqa"].each do |system_name|
    namespace system_name do
      namespace :pages do
        get :download_user_manuals
        get :notifications
        get :downloads
        get :dashboards #สำหรับรายงานผลการดำเนินงาน
        get :dashboards_pmqa_fl
        get :dashboards_pmqa_fr
        get :dashboards_risk_report

        get :dashboards_overall #สำหรับ graph

        post :search
        get :search_result
        get :master_data
        post :search_result
      end

      ["pmqa_fl", "pmqa_fr", "control"].each do |sub_system_name|
        namespace sub_system_name do
          resources :evaluate_control_reports
          resources :evaluate_controls
          resources :master_plans do
            collection do
              get "/new_by_template", to: "master_plans#new_by_template"
              get "/print/:id", to: "master_plans#print"
            end
          end
          resources :master_plan_users
          resources :follow_up_control_histories
          resources :internal_control_certificates
          resources :component_reports

          resources :plans do
         
            get "/history/:id", to: "plans#history"  
            get "/tasks", to: "plans#tasks"
            collection do
              get "/print/:id", to: "plans#print"
            
              get "/user_input/:id", to: "plans#user_input"
              patch "/user_input_update_normal/:id", to: "plans#user_input_update_normal"
              patch "/user_input_update_seven/:id", to: "plans#user_input_update_seven"
              patch "/user_input_update_op/:id", to: "plans#user_input_update_op"
              patch "/user_input_submit/:id", to: "plans#user_input_submit"
              get "/opdc_input/:id", to: "plans#opdc_input"
              patch "/opdc_input_update_normal/:id", to: "plans#opdc_input_update_normal"
              patch "/opdc_input_update_seven/:id", to: "plans#opdc_input_update_seven"
              patch "/opdc_input_submit/:id", to: "plans#opdc_input_submit"
            end
          end
          get "/plans/history/:id", to: "plans#history"
          resources :period_reports
          resources :plan_users
          resources :categories
          resources :lists
          resources :list_risk_factors
          resources :list_risk_types
          resources :list_activities
          resources :list_activity_items
          resources :tasks
          resources :plan_reports
          resources :plan_report_users
          resources :plan_report_user_comments
          resources :risk_analysis_reports
          resources :risk_analysises
          resources :task_plan_reports
          resources :task_lists
          resources :risk_management_reports
          resources :risk_managements
          resources :follow_up_risk_reports
          resources :follow_up_risks
          resources :evaluate_control_reports
          resources :evaluate_controls
          resources :follow_up_control_reports
          resources :internal_control_certificates
          resources :component_reports
          resources :follow_up_control_histories
     
        end
      end #sub_system_name

      get "/plans/form_1", to: "plans#form_1"
      get "/plans/form_2", to: "plans#form_2"
      get "/plans/form_3", to: "plans#form_3"
      get "/plans/form_4", to: "plans#form_4"
      get "/plans/form_5", to: "plans#form_5"
      get "/plans/form_6", to: "plans#form_6"
      get "/plans/form_7", to: "plans#form_7"

      get "/master_plans/new_by_template", to: "master_plans#new_by_template"
      post "/master_plans/create_by_template", to: "master_plans#create_by_template"
      get "/master_plans/print/:id", to: "master_plans#print"
      get "/plans/print/:id", to: "plans#print"
      get "/plans/view/:id", to: "plans#view"

      get "/plans/history/:id", to: "plans#history"
      get "/master_plans/edit_form_2", to: "master_plans#edit_form_2"
      get "/master_plans/edit_form_3", to: "master_plans#edit_form_3"
      get "/master_plans/edit_form_4", to: "master_plans#edit_form_4"
      get "/master_plans/edit_form_5", to: "master_plans#edit_form_5"
      get "/plan_reports/print/:id", to: "plan_reports#print"
      get "/plan_reports/:id/plan_reports_by_master_plan", to: "plan_reports#plan_reports_by_master_plan"
      resources :master_plans
      resources :fl_master_plans
      resources :pmqa_master_plans
      resources :master_plan_users
      resources :master_plan_user_comments
   
      get "/plans/:id/status", to: "plans#status"
      resources :fl_plans
      resources :pmqa_plans
      resources :plans do
        get "/tasks", to: "plans#tasks"
      
      end
      
      resources :period_reports
      resources :plan_users
      resources :plan_reports
      resources :plan_report_users
      resources :plan_report_user_comments
      resources :risk_analysis_reports
      resources :risk_analysises
      resources :task_plan_reports
      resources :task_lists
      resources :risk_management_reports
      resources :risk_managements
      resources :follow_up_risk_reports
      resources :follow_up_risks
      resources :evaluate_control_reports
      resources :evaluate_controls
      resources :follow_up_control_reports
      resources :follow_up_control_histories
      resources :internal_control_certificates
      resources :component_reports
      resources :categories
      resources :fl_categories
      resources :plan_categories
      resources :activities
      resources :lists
      resources :list_activities
      resources :list_risk_factors
      resources :list_activity_items
      resources :fl_lists
      resources :pmqa_lists
      resources :tasks
      resources :list_risk_types
      resources :category_masters
      resources :category_master_lists
      resources :category_master_list_items
   

      get "/report_os_matrix", to: "master_plans#report_os_matrix"

      get "/pmqa_fls/edit", to: "pmqa_fls#edit"
      get "/pmqa_fls/edit_by_user", to: "pmqa_fls#edit_by_user"
      get "/pmqa_fls/edit_by_opdc", to: "pmqa_fls#edit_by_opdc"
      get "/pmqa_fls/edit_by_user_7", to: "pmqa_fls#edit_by_user_7"
      get "/pmqa_fls/edit_by_opdc_7", to: "pmqa_fls#edit_by_opdc_7"
      get "/pmqa_fls/print", to: "pmqa_fls#print"
      get "/pmqa_fours/edit_by_sp_1", to: "pmqa_fours#edit_by_sp_1"
      get "/pmqa_fours/edit_by_sp_7", to: "pmqa_fours#edit_by_sp_7"
      get "/pmqa_fours/edit_by_sp_op", to: "pmqa_fours#edit_by_sp_op"
      get "/pmqa_fours/edit_by_user_1", to: "pmqa_fours#edit_by_user_1"
      get "/pmqa_fours/edit_by_user_7", to: "pmqa_fours#edit_by_user_7"
      get "/pmqa_fours/edit_by_user_op", to: "pmqa_fours#edit_by_user_op"
      get "/pmqa_fours/edit_by_opdc_1", to: "pmqa_fours#edit_by_opdc_1"
      get "/pmqa_fours/edit_by_opdc_7", to: "pmqa_fours#edit_by_opdc_7"
      get "/pmqa_fours/edit_by_opdc_op", to: "pmqa_fours#edit_by_opdc_op"
      get "/pmqa_fours/print", to: "pmqa_fours#print"
      resources :pmqa_fls
      resources :pmqa_fours

      resources :institutions
      resources :risk_types
      resources :issues
      resources :strategic_issues
      resources :kpis
      resources :fl_kpis
      resources :pmqa_bas_masters
      resources :target_kpis
      resources :responsibles
      resources :accomplices
      resources :list_types
      resources :devision_directors
      resources :attachments

      resources :users
      resources :departments
      resources :downloads
      resources :user_manuals
    end
  end

  # share service
  get "accounts/sign_in"
  post "accounts/create_session"
  get "accounts/sign_out"
  get "accounts/delete_session"
  patch "/mains/set_user_active/:id", to: "mains#set_user_active"
  delete "/mains/delete_image", to: "mains#delete_image"

  # api
  namespace :api do
    namespace :v1 do
      get "/locations", to: "locations#index"
      post "/locations", to: "locations#create"

      get "/posts", to: "posts#index"
      post "/posts", to: "posts#create"
    end
  end
  ####

  get "/pages/index", to: "pages#index"
  get "/pages/visits", to: "pages#visits"
  get "/pages/notifications", to: "pages#notifications"

  root "accounts#sign_in"

  # user
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  resources :users, only: [:index, :new, :create, :edit, :update, :destroy]
  post "/users_create", to: "users#users_create"
  post "auth_user" => "authentication#authenticate_user"
  ####

  match '*path', via: :all, to: 'pages#error_404'

  if Rails.env.production?
    mount Shrine.presign_endpoint(:cache) => "/presign"
  else
    # In development and test environment we're using filesystem storage

app/controllers/km/categories_controller.rb
class Km::CategoriesController < ApplicationController
  before_action :set_select, only: %i[new edit]

  def index
    url = URI("#{$server[@controller_title]}/api/v1/categories")
    @datas = request_api(url, "get", nil)
  end

  def show
    url = URI("#{$server[@controller_title]}/api/v1/categories/#{params["id"]}")
    @datas = request_api(url, "get", nil)
  end

  def new
    #     url = URI("#{$server[@controller_title]}/api/v1/plans")
    #     @data_plans = request_api(url,'get',nil)
    #
    #     url = URI("#{$server[@controller_title]}/api/v1/institutions")
    #     @data_institutions = request_api(url,'get',nil)
    #
    #     url = URI("#{$server[@controller_title]}/api/v1/responsibles")
    #     @data_responsibles = request_api(url,'get',nil)
    #
    #     url = URI("#{$server[@controller_title]}/api/v1/issues")
    #     @data_issues = request_api(url,'get',nil)
    #
    #     url = URI("#{$server[@controller_title]}/api/v1/kpis")
    #     @data_kpis = request_api(url,'get',nil)
    #
    #     url = URI("#{$server[@controller_title]}/api/v1/target_kpis")
    #     @data_target_kpis = request_api(url,'get',nil)
  end

  def edit
    url = URI("#{$server[@controller_title]}/api/v1/categories/#{params["id"]}")
    @datas = request_api(url, "get", nil)
  end

  def create
    # params[:category][:user_id] = $user[session.id.to_s][@controller_title]['id']
    # params[:category][:biz_id] = $user[session.id.to_s][@controller_title]['biz_id']

    url = URI("#{$server[@controller_title]}/api/v1/categories")
    @datas = request_api(url, "post", category_params)

    if @datas["status"] == "Success"
      redirect_to "/#{@controller_title}/plans/#{@datas["data"]["plan_id"]}", notice: @datas["messages"]
    else
      redirect_to "/#{@controller_title}/plans/#{params["category"]["plan_id"]}", alert: @datas["data"]
    end
  end

  def update
    p "----------------------------------------- #{params[:category]["title"]}"

    url = URI("#{$server[@controller_title]}/api/v1/categories/#{params["id"]}")
    @datas = request_api(url, "patch", category_params)

    if @datas && @datas["status"] == "Success"
      # redirect_to "/#{@controller_title}/master_plans/#{@datas['data']['plan']['master_plan_id']}", notice: @datas['message']
      redirect_to "/#{@controller_title}/categories/#{params["id"]}/edit?plan_id=#{params["category"]["plan_id"]}", notice: @datas["message"]
    else
      redirect_to "/#{@controller_title}/categories/#{params["id"]}/edit?plan_id=#{params["category"]["plan_id"]}", alert: @datas["data"]
    end
  end

  def destroy
    url = URI("#{$server[@controller_title]}/api/v1/categories/#{params["id"]}")
    @datas_ori = request_api(url, "get", nil)
    @datas = request_api(url, "delete", nil)

    url_plan = URI("#{$server[@controller_title]}/api/v1/plans/#{@datas_ori["data"]["plan_id"]}")
    @plan = request_api(url_plan, "get", nil)

    if @datas["status"] == "Success"
      redirect_to "/#{@controller_title}/master_plans/#{@plan["data"]["master_plan_id"]}", notice: @datas["message"]
    else
      redirect_to "/#{@controller_title}/master_plans/#{@plan["data"]["master_plan_id"]}", alert: t(:can_not_delete)
    end
  end

  private

  def set_select
    url = URI("#{$server[@controller_title]}/api/v1/plans/#{params["plan_id"]}")
    @data_plan = request_api(url, "get", nil)

    url = URI("#{$server[@controller_title]}/api/v1/plans")
    @data_plans = request_api(url, "get", nil)

    url = URI("#{$server[@controller_title]}/api/v1/institutions")
    @data_institutions = request_api(url, "get", nil)

    url = URI("#{$server[@controller_title]}/api/v1/responsibles")
    @data_responsibles = request_api(url, "get", nil)

    url = URI("#{$server[@controller_title]}/api/v1/issues")
    @data_issues = request_api(url, "get", nil)

    url = URI("#{$server[@controller_title]}/api/v1/kpis")
    @data_kpis = request_api(url, "get", nil)

    url = URI("#{$server[@controller_title]}/api/v1/target_kpis")
    @data_target_kpis = request_api(url, "get", nil)

    url = URI("#{$server[@controller_title]}/api/v1/activities")
    @data_activities = request_api(url, "get", nil)
  end

  def category_params
    params.require(:category).permit(:title, :cognitive, :slug, :approve, :plan_id, :institution_id, :issue_id, :kpi_id, :target_kpi_id, :kpi_title, :target_kpi_title, :responsible_id, :user_id, :biz_id,
      lists_attributes: [:id, :_destroy, :category_id, :status, :slug, :order_sort, :activity_id, :user_id, :biz_id,
        tasks_attributes: [:id, :_destroy, :category_id, :slug, :status, :order_sort, :list_id, :plan_report_id, :user_id, :biz_id]])
  end

  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to "accounts/sign_in", notice: "Please Login to view that page!"
    end
  end
end

app/controllers/km/kpis_controller.rb
class Km::KpisController < ApplicationController
  def index
    url = URI("#{$server[@controller_title]}/api/v1/kpis")
    @datas = request_api(url, "get", nil)
  end

  def show
    url = URI("#{$server[@controller_title]}/api/v1/kpis/#{params["id"]}")
    @datas = request_api(url, "get", nil)
  end

  def new
  end

  def edit
    url = URI("#{$server[@controller_title]}/api/v1/kpis/#{params["id"]}")

    @datas = request_api(url, "get", nil)

    # puts "plan edit = #{@plan['title']}"
  end

  def create
    params[:kpi][:user_id] = $user_id
    params[:kpi][:biz_id] = $biz_id

    url = URI("#{$server[@controller_title]}/api/v1/kpis")
    @datas = request_api(url, "post", kpi_params)

    if @datas["status"] == "Success"
      redirect_to "/km/kpis", notice: @datas["messages"]
    else
      redirect_to "/km/kpis/new", alert: @datas["data"]
    end
  end

  def update
    url = URI("#{$server[@controller_title]}/api/v1/kpis/#{params["id"]}")
    @datas = request_api(url, "patch", kpi_params)

    # puts "update status : #{res}"

    if @datas["status"] == "Success"
      redirect_to "/km/kpis", notice: @datas["message"]
    else
      redirect_to "/km/kpis", alert: @datas["data"]
    end
  end

  def destroy
    url = URI("#{$server[@controller_title]}/api/v1/kpis/#{params["id"]}")
    @datas = request_api(url, "delete", nil)

    if @datas["status"] == "Success"
      redirect_to "/km/kpis", notice: @datas["message"]
    else
      redirect_to "/km/kpis", alert: @datas["data"]
    end
  end

  private

  def kpi_params
    params.require(:kpi).permit(:title, :user_id, :biz_id)
  end
end

app/views/kpi/categories/_form.html.erb
<%
#init
if action_name == 'edit' || action_name == 'update'
  @plan_title = @datas['data']['plan']['title'] rescue nil
  @title = @datas['data']['title'] rescue nil
  @institution_id = @datas['data']['institution_id'] rescue nil
  @responsible_id = @datas['data']['responsible_id'] rescue nil
  @issue_id = @datas['data']['issue_id'] rescue nil
  @cognitive = @datas['data']['cognitive'] rescue nil
  @kpi_id = @datas['data']['kpi_id'] rescue nil
  @target_kpi_id = @datas['data']['target_kpi_id'] rescue nil
else
  @institution_id = @user['data']['institution']['id'] rescue nil
end

%>


  <%= form_for('category', url: "/#{gen_form[0]}/categories#{gen_form[1]}" , method: gen_form[2]) do |f| %>

    <!-- start row -->
    <div class="row">




      <!--
      <div class="col-sm-12 col-md-6">
          <label class="form-label">
              <h5><%= t(:title) %><span class="text-danger">*</span></h5>
          </label>
          <%= f.text_field :title, class: "form-control", placeholder: t(:title), value: @title %>
      </div>
    -->

      <div class="col-sm-12 col-md-12 my-6">
          <label class="form-label">
            <h5>หน่วยงาน  <span class="text-danger">*</span></h5>
          </label>
          <%= f.select "institution_id", options_for_select(@data_institutions['data'].map { |item| [item['title'], item['id']] }, (@institution_id rescue nil)), {include_blank: true}, {class: 'selectize-institution form-control', required: true } %>
      </div>





    </div>
    <!-- end row -->









    <div class="separator separator-dashed separator-border-2 my-10"></div>

    <div class="d-flex justify-content-between">
      <% if !params[:plan_id].blank? %>
        <%= f.hidden_field :plan_id, value: params[:plan_id] %>
      <% end %>

      <%= f.submit t(:saves), class: "btn btn-info" %>
    </div>





<% end #end form %>

app/views/kpi/categories/edit.html.erb
<div class="container-fluid">
  <!--begin::Header-->
  <div class="row">
    <div class="col"> 
      <div class="float-start">
        <h2 class="card-label"> <i class="fa-solid fa-circle-chevron-right"></i><%= t(:institution) %></h2> 
      </div>
      <div class="col">
        <div class="float-end">  
          <%= link_to "/#{gen_form[0]}/master_plans/#{@datas['data']['plan']['master_plan']['id']}", class: 'btn btn-light -sm' do %> <i class="fa-solid fa-angle-left"></i> <%= t(:back) %> 
          <% end %>
        </div> 
      </div>
    </div>








    <%= render 'form' %>



</div>
<!--end::Kt_content-->

app/views/kpi/categories/index.html.erb
<!--begin::Kt_conten-->
<div class="container-fluid">
	<!--begin::Header-->

	<div class="row">
		<div class="col me-5"> 
		<div class="float-start">
		<h2 class="card-label"> <i class="fa-solid fa-circle-chevron-right"></i><%= t(:forms) %><%= t(:master_plan) %> </h2> 
		</div>
		<div class="col mb-5">
			<div class="float-xxl-end float-xl-end float-lg-end  float-md-end float-sm-none">
				<!--button:header-->
				<a href="/<%= @controller_title %>/categories/new" class="btn btn-info -sm"><i class="fa-solid fa-circle-plus fa-4x"></i><%= t(:create)%></a>
			</div> 
		</div>
		</div>
	</div>
<!--end:Header-->

<!--begin:Content-->
	<div class="row">

		<% @datas['data'].each do |item| %>

			<div class="col-lg-6">

			<div class="card card-custom gutter-b">			
					<!--begin::Header-Content-->
					<div class="card-master">	
								<div class="row mt-5">
								<div class="col-8"> 
									<div class="row"> 
										<div class="col-1"> 
											<i class="fa-solid fa-file-lines fa-2x"></i>
										</div>
										<div class="col float-start ms-2">
											<h6><%= item['title'] %></p></h6>
										</div>
									</div>
								</div>						
								<div class="col-sm-4">
								<div class="float-xxl-end float-xl-end float-lg-end  float-md-end float-sm-none">

									<%= link_to "/#{@controller_title}/categories/#{item['id']}", method: :delete, title: t(:delete),  data: { confirm: 'ต้องการลบใช่หรือไม่?' } , class: "text-center btn btn-sm btn-light" do %>
										<i class="fa-regular fa-trash-can"></i><%#= t(:delete) %>
									<% end %>

									
									<!--
									<%= link_to "/#{@controller_title}/categories_clone?id=#{item['id']}" , class: "btn btn-sm btn-light", title: t(:clone) do %>
										<i class="fa-regular fa-clone"></i><%#= t(:clone) %>
									<% end %>
									-->
							
								</div>
								</div>			 		  
							</div>											
					</div>
					<!--end ::Header-Content-->

					<!--begin:content-details-->
					<div class="card-content">
					 	<div class="mb-4">
					 		<p><b><%= t(:category_title)%> : </b> <%= item['title'] %></p>
							<p><b><%= t(:institution)%> : </b> <%= item['institution']['title'] %></p>
							<p><b><%= t(:responsible)%> : </b> <%= item['responsible']['title'] %></p>
							<p><b><%= t(:issue)%> : </b> <%= item['issue']['title'] %></p>
							<p><b><%= t(:cognitive)%> : </b> <%= item['cognitive'] %></p>
							<p><b><%= t(:kpi)%> : </b> <%= item['kpi']['title'] %></p>
							<p><b><%= t(:target_kpi)%> : </b> <%= item['target_kpi']['title'] %></p>
					 	</div>
						 
						 <a href="/<%= @controller_title %>/categories/<%= item['id'] %>/edit" class="btn-info btn-sm text-white mt-3 d-block-inline"><%= t(:edit) %> <i class="fa-solid fa-angle-right text-white"></i>
						 </a>

					</div>
					<!--end::content-details-->
				</div> 
			</div> 

		<% end %>
	</div> 
<!--end:Content-->

</div>
<!-- end::Kt_conten -->

app/views/kpi/categories/new.html.erb
<div class="container-fluid">

  <div class="d-flex justify-content-between">
          <h1 class="card-label"> <i class="fa-solid fa-circle-chevron-right"></i><%= t(:institution) %></h1> 

          <%= link_to "/#{gen_form[0]}/master_plans/#{params['master_plan_id']}", class: 'btn btn-light -sm' do %> <i class="fa-solid fa-angle-left"></i> <%= t(:back) %>
          <% end %>
  </div>


    <%= render 'form' %>

</div>
<!--end::Kt_content-->

app/views/kpi/categories/show.html.erb
<!--begin::Kt_content-->
<div class="container-fluid">
        <!--begin::Row-->
        <div class="row">
        <div class="col"> 
                <div class="float-start">
                <h2 class="card-label"> <i class="fa-solid fa-circle-chevron-right"></i><%= t(:detail) %><%= t(:forms) %><%= t(:master_plan) %></h2> 
                </div>
        <div class="col">
        <div class="float-end">  
                <%= link_to km_categories_path(@category), class: 'btn btn-light -sm' do %> <i class="fa-solid fa-angle-left"></i></i> <%= t(:back) %> </i> <% end %>
        </div> 
        </div>
        </div>

        <div class="row">
                <div class="col"> 
                        <div class="card-show">
                                <div class="row">
                                        <div class="col mb-5"> 
                                                <div class="float-start">
                                                <h4 class="card-label"> <i class="fa-solid fa-file-lines fa-1x"></i> <%= @datas['data']['title'] %>
                                                </div>          
                                        </div>
                                        </div>
                                        <div class="col ms-5"> 
                                        <p><b><%= t(:plan_title)%> : </b> <%= @datas['data']['plan']['title'] %></p>
                                        <p><b><%= t(:institution)%> : </b> <%= @datas['data']['institution']['title'] %></p>
                                        <p><b><%= t(:responsible)%> : </b> <%= @datas['data']['responsible']['title'] %></p>
                                        <p><b><%= t(:issue)%> : </b> <%= @datas['data']['issue']['title'] %></p>
                                        <p><b><%= t(:cognitive)%> : </b> <%= @datas['data']['cognitive'] %></p>
                                        <p><b><%= t(:kpi)%> : </b> <%= @datas['data']['kpi']['title'] %></p>
                                        <p><b><%= t(:target_kpi)%> : </b> <%= @datas['data']['target_kpi']['title'] %></p>
                                        <p><b><%= t(:created_at)%> : </b> <%= @datas['data']['created_at'] %></p>
                                        <p><b><%= t(:updated_at)%> : </b> <%= @datas['data']['updated_at'] %></p>
                                        </div>
                                        <div class="col ms-5 mt-5"> 
                                                <div class="card-show">
                                                <div class="table-responsive py-5">
                                                                <table class="table table-row-dashed table-row-gray-300 align-middle gs-0 gy-4">
                                                                        <thead>
                                                                        <tr class="fw-bolder text-muted">
                                                                                        <th><h6><%= t(:id) %><h6></th>
                                                                                        <th class="min-w-200px"><h6><%= t(:activity) %><h6></th>
                                                                                        <th class="min-w-100px"><h6><%= t(:list_periods) %><h6></th>
                                                                                        <th class="min-w-100px"><h6><%= t(:list_kpis) %><h6></th>
                                                                                        <th class="min-w-100px"><h6><%= t(:list_target_kpis) %><h6></th>
                                                                                        <th class="min-w-100px"><h6><%= t(:list_target_groups) %><h6></th>
                                                                                        <th class="min-w-100px"><h6><%= t(:list_responsibles) %><h6></th>
                                                                                        <th class="min-w-100px"><h6><%= t(:list_notes) %><h6></th>
                                                                                </tr>
                                                                        </thead>
                                                                        <tbody>
                                                                                <td scope="row"><% @datas['data']['lists'].each_with_index do |item_a,idx| %></t>
                                                                                        <tr>
                                                                                                <td>  <%= idx +1 %></td>
                                                                                                <td>  <%= item_a['activity']['title'] %></td>
                                                                                                <td> </td>
                                                                                                <td> </td>
                                                                                                <td> </td>
                                                                                                <td> </td>
                                                                                                <td> </td>
                                                                                                <td> </td>
                                                                                        
                                                                                                <% end %>
                                                                                        </tr>
                                                                                </tbody>
                                                                </tbody>
                                                                </table>
                                                        </div>
                                        
                                                </div>
                        </div>
        </div>
                </div>
</div>
<!--end::Kt_content-->