config/routes.rb
Rails.application.routes.draw do


  namespace :km do
    get 'user_manuals/index'
    get 'user_manuals/new'
    get 'user_manuals/edit'
  end
  namespace :risk do
    get 'user_manuals/index'
    get 'user_manuals/new'
    get 'user_manuals/edit'
  end
  namespace :pmqa do
    get 'user_manuals/index'
    get 'user_manuals/new'
    get 'user_manuals/edit'
  end
  namespace :kpi do
    get 'user_manuals/index'
    get 'user_manuals/edit'
    get 'user_manuals/new'
  end
  namespace :risk do
    get 'list_risk_types/index'
    get 'list_risk_types/show'
    get 'list_risk_types/edit'
    get 'list_risk_types/new'
  end
  namespace :risk do
    get 'list_risk_factors/index'
    get 'list_risk_factors/show'
    get 'list_risk_factors/edit'
    get 'list_risk_factors/new'
  end
  namespace :kpi do
    get 'period_reports/index'
    get 'period_reports/show'
    get 'period_reports/new'
    get 'period_reports/edit'
  end
  namespace :risk do
    namespace :control do
      get 'period_reports/index'
      get 'period_reports/show'
      get 'period_reports/new'
      get 'period_reports/edit'
    end
  end
  get 'errors/not_found'
  get 'errors/internal_server_error'
  resources :locations
  resources :bizs
  ["km", "kpi", "risk", "pmqa"].each do |system_name|
    namespace system_name do
      namespace :pages do
        get :download_user_manuals
        get :notifications
        get :downloads
        get :dashboards #สำหรับรายงานผลการดำเนินงาน
        get :dashboards_pmqa_fl
        get :dashboards_pmqa_fr
        get :dashboards_risk_report

        get :dashboards_overall #สำหรับ graph

        post :search
        get :search_result
        get :master_data
        post :search_result
      end

      ["pmqa_fl", "pmqa_fr", "control"].each do |sub_system_name|
        namespace sub_system_name do
          resources :evaluate_control_reports
          resources :evaluate_controls
          resources :master_plans do
            collection do
              get "/new_by_template", to: "master_plans#new_by_template"
              get "/print/:id", to: "master_plans#print"
            end
          end
          resources :master_plan_users
          resources :follow_up_control_histories
          resources :internal_control_certificates
          resources :component_reports

          resources :plans do
         
            get "/history/:id", to: "plans#history"  
            get "/tasks", to: "plans#tasks"
            collection do
              get "/print/:id", to: "plans#print"
            
              get "/user_input/:id", to: "plans#user_input"
              patch "/user_input_update_normal/:id", to: "plans#user_input_update_normal"
              patch "/user_input_update_seven/:id", to: "plans#user_input_update_seven"
              patch "/user_input_update_op/:id", to: "plans#user_input_update_op"
              patch "/user_input_submit/:id", to: "plans#user_input_submit"
              get "/opdc_input/:id", to: "plans#opdc_input"
              patch "/opdc_input_update_normal/:id", to: "plans#opdc_input_update_normal"
              patch "/opdc_input_update_seven/:id", to: "plans#opdc_input_update_seven"
              patch "/opdc_input_submit/:id", to: "plans#opdc_input_submit"
            end
          end
          get "/plans/history/:id", to: "plans#history"
          resources :period_reports
          resources :plan_users
          resources :categories
          resources :lists
          resources :list_risk_factors
          resources :list_risk_types
          resources :list_activities
          resources :list_activity_items
          resources :tasks
          resources :plan_reports
          resources :plan_report_users
          resources :plan_report_user_comments
          resources :risk_analysis_reports
          resources :risk_analysises
          resources :task_plan_reports
          resources :task_lists
          resources :risk_management_reports
          resources :risk_managements
          resources :follow_up_risk_reports
          resources :follow_up_risks
          resources :evaluate_control_reports
          resources :evaluate_controls
          resources :follow_up_control_reports
          resources :internal_control_certificates
          resources :component_reports
          resources :follow_up_control_histories
     
        end
      end #sub_system_name

      get "/plans/form_1", to: "plans#form_1"
      get "/plans/form_2", to: "plans#form_2"
      get "/plans/form_3", to: "plans#form_3"
      get "/plans/form_4", to: "plans#form_4"
      get "/plans/form_5", to: "plans#form_5"
      get "/plans/form_6", to: "plans#form_6"
      get "/plans/form_7", to: "plans#form_7"

      get "/master_plans/new_by_template", to: "master_plans#new_by_template"
      post "/master_plans/create_by_template", to: "master_plans#create_by_template"
      get "/master_plans/print/:id", to: "master_plans#print"
      get "/plans/print/:id", to: "plans#print"
      get "/plans/view/:id", to: "plans#view"

      get "/plans/history/:id", to: "plans#history"
      get "/master_plans/edit_form_2", to: "master_plans#edit_form_2"
      get "/master_plans/edit_form_3", to: "master_plans#edit_form_3"
      get "/master_plans/edit_form_4", to: "master_plans#edit_form_4"
      get "/master_plans/edit_form_5", to: "master_plans#edit_form_5"
      get "/plan_reports/print/:id", to: "plan_reports#print"
      get "/plan_reports/:id/plan_reports_by_master_plan", to: "plan_reports#plan_reports_by_master_plan"
      resources :master_plans
      resources :fl_master_plans
      resources :pmqa_master_plans
      resources :master_plan_users
      resources :master_plan_user_comments
   
      get "/plans/:id/status", to: "plans#status"
      resources :fl_plans
      resources :pmqa_plans
      resources :plans do
        get "/tasks", to: "plans#tasks"
      
      end
      
      resources :period_reports
      resources :plan_users
      resources :plan_reports
      resources :plan_report_users
      resources :plan_report_user_comments
      resources :risk_analysis_reports
      resources :risk_analysises
      resources :task_plan_reports
      resources :task_lists
      resources :risk_management_reports
      resources :risk_managements
      resources :follow_up_risk_reports
      resources :follow_up_risks
      resources :evaluate_control_reports
      resources :evaluate_controls
      resources :follow_up_control_reports
      resources :follow_up_control_histories
      resources :internal_control_certificates
      resources :component_reports
      resources :categories
      resources :fl_categories
      resources :plan_categories
      resources :activities
      resources :lists
      resources :list_activities
      resources :list_risk_factors
      resources :list_activity_items
      resources :fl_lists
      resources :pmqa_lists
      resources :tasks
      resources :list_risk_types
      resources :category_masters
      resources :category_master_lists
      resources :category_master_list_items
   

      get "/report_os_matrix", to: "master_plans#report_os_matrix"

      get "/pmqa_fls/edit", to: "pmqa_fls#edit"
      get "/pmqa_fls/edit_by_user", to: "pmqa_fls#edit_by_user"
      get "/pmqa_fls/edit_by_opdc", to: "pmqa_fls#edit_by_opdc"
      get "/pmqa_fls/edit_by_user_7", to: "pmqa_fls#edit_by_user_7"
      get "/pmqa_fls/edit_by_opdc_7", to: "pmqa_fls#edit_by_opdc_7"
      get "/pmqa_fls/print", to: "pmqa_fls#print"
      get "/pmqa_fours/edit_by_sp_1", to: "pmqa_fours#edit_by_sp_1"
      get "/pmqa_fours/edit_by_sp_7", to: "pmqa_fours#edit_by_sp_7"
      get "/pmqa_fours/edit_by_sp_op", to: "pmqa_fours#edit_by_sp_op"
      get "/pmqa_fours/edit_by_user_1", to: "pmqa_fours#edit_by_user_1"
      get "/pmqa_fours/edit_by_user_7", to: "pmqa_fours#edit_by_user_7"
      get "/pmqa_fours/edit_by_user_op", to: "pmqa_fours#edit_by_user_op"
      get "/pmqa_fours/edit_by_opdc_1", to: "pmqa_fours#edit_by_opdc_1"
      get "/pmqa_fours/edit_by_opdc_7", to: "pmqa_fours#edit_by_opdc_7"
      get "/pmqa_fours/edit_by_opdc_op", to: "pmqa_fours#edit_by_opdc_op"
      get "/pmqa_fours/print", to: "pmqa_fours#print"
      resources :pmqa_fls
      resources :pmqa_fours

      resources :institutions
      resources :risk_types
      resources :issues
      resources :strategic_issues
      resources :kpis
      resources :fl_kpis
      resources :pmqa_bas_masters
      resources :target_kpis
      resources :responsibles
      resources :accomplices
      resources :list_types
      resources :devision_directors
      resources :attachments

      resources :users
      resources :departments
      resources :downloads
      resources :user_manuals
    end
  end

  # share service
  get "accounts/sign_in"
  post "accounts/create_session"
  get "accounts/sign_out"
  get "accounts/delete_session"
  patch "/mains/set_user_active/:id", to: "mains#set_user_active"
  delete "/mains/delete_image", to: "mains#delete_image"

  # api
  namespace :api do
    namespace :v1 do
      get "/locations", to: "locations#index"
      post "/locations", to: "locations#create"

      get "/posts", to: "posts#index"
      post "/posts", to: "posts#create"
    end
  end
  ####

  get "/pages/index", to: "pages#index"
  get "/pages/visits", to: "pages#visits"
  get "/pages/notifications", to: "pages#notifications"

  root "accounts#sign_in"

  # user
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  resources :users, only: [:index, :new, :create, :edit, :update, :destroy]
  post "/users_create", to: "users#users_create"
  post "auth_user" => "authentication#authenticate_user"
  ####

  match '*path', via: :all, to: 'pages#error_404'

  if Rails.env.production?
    mount Shrine.presign_endpoint(:cache) => "/presign"
  else
    # In development and test environment we're using filesystem storage

app/controllers/km/kpis_controller.rb
class Km::KpisController < ApplicationController
  def index
    url = URI("#{$server[@controller_title]}/api/v1/kpis")
    @datas = request_api(url, "get", nil)
  end

  def show
    url = URI("#{$server[@controller_title]}/api/v1/kpis/#{params["id"]}")
    @datas = request_api(url, "get", nil)
  end

  def new
  end

  def edit
    url = URI("#{$server[@controller_title]}/api/v1/kpis/#{params["id"]}")

    @datas = request_api(url, "get", nil)

    # puts "plan edit = #{@plan['title']}"
  end

  def create
    params[:kpi][:user_id] = $user_id
    params[:kpi][:biz_id] = $biz_id

    url = URI("#{$server[@controller_title]}/api/v1/kpis")
    @datas = request_api(url, "post", kpi_params)

    if @datas["status"] == "Success"
      redirect_to "/km/kpis", notice: @datas["messages"]
    else
      redirect_to "/km/kpis/new", alert: @datas["data"]
    end
  end

  def update
    url = URI("#{$server[@controller_title]}/api/v1/kpis/#{params["id"]}")
    @datas = request_api(url, "patch", kpi_params)

    # puts "update status : #{res}"

    if @datas["status"] == "Success"
      redirect_to "/km/kpis", notice: @datas["message"]
    else
      redirect_to "/km/kpis", alert: @datas["data"]
    end
  end

  def destroy
    url = URI("#{$server[@controller_title]}/api/v1/kpis/#{params["id"]}")
    @datas = request_api(url, "delete", nil)

    if @datas["status"] == "Success"
      redirect_to "/km/kpis", notice: @datas["message"]
    else
      redirect_to "/km/kpis", alert: @datas["data"]
    end
  end

  private

  def kpi_params
    params.require(:kpi).permit(:title, :user_id, :biz_id)
  end
end

app/controllers/km/responsibles_controller.rb
class Km::ResponsiblesController < ApplicationController
  def index
    url = URI("#{$server[@controller_title]}/api/v1/responsibles")

    @datas = request_api(url, "get", nil)
  end

  def show
    url = URI("#{$server[@controller_title]}/api/v1/responsibles/#{params["id"]}")

    @datas = request_api(url, "get", nil)
  end

  def new
  end

  def edit
    url = URI("#{$server[@controller_title]}/api/v1/responsibles/#{params["id"]}")

    @datas = request_api(url, "get", nil)

    # puts "plan edit = #{@plan['title']}"
  end

  def create
    params[:responsible][:user_id] = $user_id
    params[:responsible][:biz_id] = $biz_id

    url = URI("#{$server[@controller_title]}/api/v1/responsibles")
    @datas = request_api(url, "post", responsible_params)

    if @datas["status"] == "Success"
      redirect_to "/#{@controller_title}/responsibles", notice: @datas["messages"]
    else
      redirect_to "/#{@controller_title}/responsibles/new", alert: @datas["data"]
    end
  end

  def update
    url = URI("#{$server[@controller_title]}/api/v1/responsibles/#{params["id"]}")
    @datas = request_api(url, "patch", responsible_params)

    # puts "update status : #{res}"

    if @datas["status"] == "Success"
      redirect_to "/#{@controller_title}/responsibles", notice: @datas["message"]
    else
      redirect_to "/#{@controller_title}/responsibles", alert: @datas["data"]
    end
  end

  def destroy
    url = URI("#{$server[@controller_title]}/api/v1/responsibles/#{params["id"]}")
    @datas = request_api(url, "delete", nil)

    if @datas["status"] == "Success"
      redirect_to "/#{@controller_title}/responsibles", notice: @datas["message"]
    else
      redirect_to "/#{@controller_title}/responsibles", alert: @datas["data"]
    end
  end

  private

  def responsible_params
    params.require(:responsible).permit(:title, :order_sort, :user_id, :biz_id)
  end
end

app/controllers/kpi/activities_controller.rb
class Kpi::ActivitiesController < ApplicationController
  def index
    url = URI("#{$server[@controller_title]}/api/v1/activities")

    @datas = request_api(url, "get", nil)
  end

  def show
    url = URI("#{$server[@controller_title]}/api/v1/activities/#{params["id"]}")
    @datas = request_api(url, "get", nil)
  end

  def new
  end

  def edit
    url = URI("#{$server[@controller_title]}/api/v1/activities/#{params["id"]}")

    @datas = request_api(url, "get", nil)

    # puts "plan edit = #{@plan['title']}"
  end

  def create
    params[:activity][:user_id] = $user_id
    params[:activity][:biz_id] = $biz_id

    url = URI("#{$server[@controller_title]}/api/v1/activities")
    @datas = request_api(url, "post", activity_params)

    if @datas["status"] == "Success"
      redirect_to "/kpi/activities", notice: @datas["messages"]
    else
      redirect_to "/kpi/activities/new", alert: @datas["data"]
    end
  end

  def update
    url = URI("#{$server[@controller_title]}/api/v1/activities/#{params["id"]}")
    @datas = request_api(url, "patch", activity_params)

    # puts "update status : #{res}"

    if @datas["status"] == "Success"
      redirect_to "/kpi/activities", notice: @datas["message"]
    else
      redirect_to "/kpi/activities", alert: @datas["data"]
    end
  end

  def destroy
    url = URI("#{$server[@controller_title]}/api/v1/activities/#{params["id"]}")
    @datas = request_api(url, "delete", nil)

    if @datas["status"] == "Success"
      redirect_to "/kpi/activities", notice: @datas["message"]
    else
      redirect_to "/kpi/activities", alert: @datas["data"]
    end
  end

  private

  def activity_params
    params.require(:activity).permit(:title, :order_sort, :user_id, :biz_id)
  end

  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to "accounts/sign_in", notice: "Please Login to view that page!"
    end
  end
end

app/controllers/kpi/activitys_controller.rb
class Kpi::ActivitysController < ApplicationController
  def index
    url = URI("#{$server[@controller_title]}/api/v1/activitys")

    @datas = request_api(url, "get", nil)
  end

  def show
    url = URI("#{$server[@controller_title]}/api/v1/activitys/#{params["id"]}")

    @datas = request_api(url, "get", nil)
  end

  def new
  end

  def edit
    url = URI("#{$server[@controller_title]}/api/v1/activitys/#{params["id"]}")

    @datas = request_api(url, "get", nil)

    # puts "plan edit = #{@plan['title']}"
  end

  def create
    params[:activity][:user_id] = $user_id
    params[:activity][:biz_id] = $biz_id

    url = URI("#{$server[@controller_title]}/api/v1/activitys")
    @datas = request_api(url, "post", activity_params)

    if @datas["status"] == "Success"
      redirect_to "/kpi/activitys", notice: @datas["messages"]
    else
      redirect_to "/kpi/activitys/new", alert: @datas["data"]
    end
  end

  def update
    url = URI("#{$server[@controller_title]}/api/v1/activitys/#{params["id"]}")
    @datas = request_api(url, "patch", activity_params)

    # puts "update status : #{res}"

    if @datas["status"] == "Success"
      redirect_to "/kpi/activitys", notice: @datas["message"]
    else
      redirect_to "/kpi/activitys", alert: @datas["data"]
    end
  end

  def destroy
    url = URI("#{$server[@controller_title]}/api/v1/activitys/#{params["id"]}")
    @datas = request_api(url, "delete", nil)

    if @datas["status"] == "Success"
      redirect_to "/kpi/activitys", notice: @datas["message"]
    else
      redirect_to "/kpi/activitys", alert: @datas["data"]
    end
  end

  private

  def activity_params
    params.require(:activity).permit(:title, :user_id, :biz_id)
  end
end

app/views/kpi/responsibles/edit.html.erb
<!--begin::Kt_content-->
<div class="container-fluid">
      <!--begin::Header-->
        <div class="row">
            <div class="col"> 
                  <div class="float-start">
                        <h2 class="card-label"> <i class="fa-solid fa-circle-chevron-right"></i><%= t(:edit) %><%= t(:responsible) %></h2> 
                  </div>
            <div class="col">
              <div class="float-end">  
                    <%= link_to km_responsibles_path(@kpi), class: 'btn btn-light -sm' do %> <i class="fa-solid fa-angle-left"></i></i> <%= t(:back) %> </i> <% end %>
              </div> 
            </div>
       </div>
      <!--end:Header-->
      <!--begin:Content-->
       <div class="row">
            <div class="col">
                   <div class="card-show">
                        <%= form_for('kpi', url: "/#{@controller_title}/responsibles/#{@datas['data']['id']}" , method: :patch) do |f| %>
                        <div class="row">                                                                      
                              <div class="col-11 mt-5 ms-5">
                              
                              <label for="formGroupExampleInput" class="form-label"> <h5> <%= t(:responsible) %> <span class="text-danger">*</span> </h5></label>
                              <%= f.text_field :title, class: "form-control", placeholder: t(:title), value: @datas['data']['title'] %>   
                              </div>                                    
                              
                              <div class="col-11 mt-5 ms-5 mb-5">
                              <div class="float-xxl-end float-xl-end float-lg-end  float-md-end float-sm-none">
                                    <!--button:content-->
                                    <%= f.submit t('saves'), class: "btn btn-info" %></div>
                              </div>  
                        </div>


                   <% end %>
                   </div>
            </div>
      </div>
      <!--end:Content-->
</div>
<!--end::Kt_content-->

app/views/kpi/responsibles/index.html copy.erb
<!--begin::Kt_conten-->
<div class="content flex-row-fluid" id="kt_content">
      <!--begin::Row-->
      <div class="row">
            <!--begin::Col_12-->
            <div class="col-12">

                        <!--begin::Card_card_custom-->
                        <div class="card card-custom gutter-b">

                              <!--begin::Card-Header-->
                              <div class="card-header">
                                    <!--begin::Card-Title-->
                                    <div class="card-title">
                                          <h3 class="card-label">
                                                  <%= t(:show) %> <%= t(:responsible) %>
                                          </h3>
                                   
                                    </div>
                                    <!--end::Card-Title-->
                                   
                                    <!-- begin::Card-Toolbar -->
                                    <div class="card-toolbar">

                                    </div>
                                    <!-- end::Card-Toolbar -->
                                 
                              </div>
                              <!--end::Card-Header-->

                              <!--begin::Card-Body-->
                              <div class="card-body">
                              
                                        <table class="table table-borderless">
                                            <thead>
                                                  <tr>

                                                      <th></th>
                                    
                                                      <th></th>
                                                  </tr>
                                            </thead>
                                            <tbody>
                                                <% @datas['data'].each do |item| %>
                                                    <tr>

                                                          <td><%= item['title'] %></td>
                                                
                                                          <td>
                                                              <%= link_to  km_responsible_path(item['id']) , class: "btn btn-sm btn-clean btn-icon mr-2" do %>

                                                                <span class="svg-icon svg-icon-primary svg-icon-2x"><!--begin::Svg Icon | path:/var/www/preview.keenthemes.com/metronic/releases/2021-01-27-044720/theme/html/demo2/dist/../src/media/svg/icons/General/Visible.svg--><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                                                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                                  <rect x="0" y="0" width="24" height="24"/>
                                                                  <path d="M3,12 C3,12 5.45454545,6 12,6 C16.9090909,6 21,12 21,12 C21,12 16.9090909,18 12,18 C5.45454545,18 3,12 3,12 Z" fill="#000000" fill-rule="nonzero" opacity="0.3"/>
                                                                  <path d="M12,15 C10.3431458,15 9,13.6568542 9,12 C9,10.3431458 10.3431458,9 12,9 C13.6568542,9 15,10.3431458 15,12 C15,13.6568542 13.6568542,15 12,15 Z" fill="#000000" opacity="0.3"/>
                                                                </g>
                                                                </svg>
                                                              <% end %>
        
                                                              <%= link_to km_responsible_path(item['id']), method: :delete, data: { confirm: 'ต้องการลบใช่หรือไม่?' } , class: "btn btn-sm btn-clean btn-icon" do %>
                                                              <span class="svg-icon svg-icon-md">
                                                                  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">\
                                                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                                        <rect x="0" y="0" width="24" height="24"/>
                                                                        <path d="M6,8 L6,20.5 C6,21.3284271 6.67157288,22 7.5,22 L16.5,22 C17.3284271,22 18,21.3284271 18,20.5 L18,8 L6,8 Z" fill="#000000" fill-rule="nonzero"/>
                                                                        <path d="M14,4.5 L14,4 C14,3.44771525 13.5522847,3 13,3 L11,3 C10.4477153,3 10,3.44771525 10,4 L10,4.5 L5.5,4.5 C5.22385763,4.5 5,4.72385763 5,5 L5,5.5 C5,5.77614237 5.22385763,6 5.5,6 L18.5,6 C18.7761424,6 19,5.77614237 19,5.5 L19,5 C19,4.72385763 18.7761424,4.5 18.5,4.5 L14,4.5 Z" fill="#000000" opacity="0.3"/>
                                                                     </g>
                                                                  </svg>
                                                              </span>
                                                              <% end %>
                                                              <%= link_to :edit, km_responsible_path(item['id'])+"/edit", class: 'btn btn-warning btn-sm mb-1' %>
                                                          </td>
     
                                                    </tr>
                                                  <% end %>
                                            </tbody>   
                                        </table>
                                </div>
                                <!--end::Card-Body-->

                          </div>
                          <!--end::Card_card_custom-->
            </div>
            <!--end::Col_12-->
        </div>
        <!--end::Row-->
</div>
<!-- end::Kt_conten -->

app/views/kpi/responsibles/index.html.erb
<!--begin::Kt_conten-->
<div class="container-fluid">
	<!--begin::Header-->

	<div class="row">
		<div class="col mb-5"> 
		<div class="float-start">
		<h2 class="card-label"> <i class="fa-solid fa-circle-chevron-right"></i><%= t(:responsible) %></h2> 
		</div>
		<div class="col mb-5">
            <div class="float-xxl-end float-xl-end float-lg-end  float-md-end float-sm-none">
            <!--button:header-->
              <%= link_to "/#{@controller_title}/pages/master_data", class: 'btn btn-light -sm' do %> <i class="fa-solid fa-angle-left"></i> <%= t(:back) %> <% end %>
            </div> 
		</div>
		</div>
	</div>
<!--end:Header-->

<!--begin:Content-->

<div class="card-show mb-5 mb-xl-8">
<!--begin::Header-->
<div class="card-header border-0 pt-5">
      <h3 class="card-title align-items-start flex-column">
            <span class="card-label fw-bolder fs-3 mb-1"><%= t(:listing_name) %><%= t(:responsible) %></span>
      </h3>
     
<!--end::Header-->
<!--begin::Body-->
<div class="card-body pt-3">
      <!--begin::Table container-->
      <div class="table-responsive">
            <!--begin::Table-->
            <table class="table table-row-dashed table-row-gray-300 align-middle gs-0 gy-4">
                  <!--begin::Table head-->
                  <thead>
                        <tr class="border-0">
                              <th class="p-0 min-w-250px"></th>
                              <th class="p-0 min-w-100px text-end"></th>
                        </tr>
                  </thead>
                  <!--end::Table head-->
                  <!--begin::Table body-->
                  <tbody>
                  <% @datas['data'].each do |item| %>
                        <tr>
                              <td>
                                    <span class="fw-bolder text-gray-800 ps-3"><%= item['title'] %></span>
                              </td>

                              <td class="text-end">
                                    
                              <%= link_to "", km_responsible_path(item['id'])+"/edit", class: 'fa-solid fa-pen-to-square' %>
                              <%= link_to "", km_responsible_path(item['id']), method: :delete, data: { confirm: 'ต้องการลบใช่หรือไม่?' } , class: "fa-regular fa-trash-can"  %>
                              </td>
                        </tr>
           
                        <% end %>
                  </tbody>
                  <!--end::Table body-->
            </table>
            <!--end::Table-->
      </div>
      <div class="float-xxl-end float-xl-end float-lg-end  float-md-end float-sm-none mt-5">
				<!--button:header-->
                        <a href="/<%= @controller_title %>/responsibles/new" class="btn btn-info -sm"><i class="fa-solid fa-circle-plus fa-4x"></i><%= t(:add)%><%= t(:responsible) %></a>
			</div> 
      <!--end::Table container-->
</div>
<!--begin::Body-->
</div>

<!--end:Content-->


</div>
<!-- end::Kt_conten -->

app/views/kpi/responsibles/show.html.erb
<!--begin::Kt_content-->
<div class="content flex-row-fluid" id="kt_content">
		  <div class="row">
            <div class="col-12">

                  <!--begin::Card_card_custom-->
                  <div class="card card-custom gutter-b">

                          <!--begin::Header-->
                          <div class="card-header">
                                  <!--begin::Card Title-->
                                  <div class="card-title">
                                            <h3 class="card-label">
                                                <%= t(:show) %> <%= t(:responsible) %>

                                            </h3>

                                  </div>
                                  <!--end::Card Title-->

                                  <!--begin::Toolbar-->
                                  <div class="card-toolbar">
                                          <%= link_to km_responsibles_path(@kpi), class: 'btn btn-light bg-white mb-2' do %>
                                                  <i class="ki ki-bold-arrow-back icon-sm"></i> <%= t(:back) %>
                                          <% end %>
          
                                  </div>
                                  <!--end::Toolbar-->
                          </div>
                          <!--end::Header-->

                          <!--begin::CardBody-->
                          <div class="card-body">
                                      <p><b><%= t(:title)%> : </b> <%= @datas['data']['title'] %></p>
                                      <p><b><%= t(:created_at)%> : </b> <%= @datas['data']['created_at'] %></p>
                                      <p><b><%= t(:updated_at)%> : </b> <%= @datas['data']['updated_at'] %></p>
          
                          </div>
                          <!--end::CardBody-->

                          <!--begin::Foolter-->
                          <div class="card-footer d-flex justify-content-between">

                          </div>
                          <!--end::Foolter-->

                    </div> <br />
                    <!--end::Card_card_custom-->

              </div>
              <!--end::Col_12-->
        </div>
        <!--end::Row-->
</div>
<!--end::Kt_content-->